name: Deploy to WordPress.org
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release tag'
        required: true
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Composer dependencies
        run: |
          composer install -vv --ansi --no-dev --prefer-dist
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@1.5.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          ASSETS_DIR: assets
          VERSION: ${{ github.event.inputs.releaseVersion }}
